language: c

before_install:
  sudo apt-get update && sudo apt-get -y upgrade && sudo apt-get -y install libedit-dev

script:
  clang -std=c99 -Wall main.c mpc.c -ledit -lm -o parsing


compiler:
  - clang

